spring:
  datasource:
    url: jdbc:h2:./build/DB/dbdevDb1;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=TRUE # jdbc:h2:~/devDb1;MODE=PostgreSQL;AUTO_SERVER=TRUE
    username: sa
    password: ''

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    history-level: full
    job-execution:
      deployment-aware: false
#spring:
#  jersey:
#    application-path: /rest
